services:
  - type: web
    name: smarttrip
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb://localhost:27017/smarttrip
      - key: JWT_SECRET
        value: your_jwt_secret_key_here
      - key: RAZORPAY_KEY_ID
        value: rzp_test_RhVYKPOupv38C4
      - key: RAZORPAY_KEY_SECRET
        value: YfX6poJ2kdF26aKSAIg2Ljd8
      - key: GOOGLE_MAPS_API_KEY
        value: your_google_places_api_key_here
      - key: ADMIN_SECRET_KEY
        value: smarttrip_admin_2024
      - key: STRIPE_SECRET_KEY
        value: your_stripe_secret_key_here
      - key: MOCK_PAYMENT
        value: "true"
