services:
  - type: web
    name: smarttrip
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: MONGO_URI
        value: mongodb+srv://saumilnainuji667_db_user:SaumilNainuji5533@cluster0.e2vs2aj.mongodb.net/SmartTrip?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: your_jwt_secret_key_here
      - key: RAZORPAY_KEY_ID
        value: rzp_test_RhVYKPOupv38C4
      - key: RAZORPAY_KEY_SECRET
        value: YfX6poJ2kdF26aKSAIg2Ljd8
      - key: GOOGLE_MAPS_API_KEY
        value: your_google_places_api_key_here
      - key: ADMIN_SECRET_KEY
        value: smarttrip_admin_2024
      - key: STRIPE_SECRET_KEY
        value: your_stripe_secret_key_here
      - key: MOCK_PAYMENT
        value: "true"
