const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Place = require('./models/Place');
const User = require('./models/User');

// Load env vars
dotenv.config();

// Connect to DB
mongoose.connect(process.env.MONGO_URI);

const places = [
    {
        name: "Santorini Sunset Views",
        country: "Greece",
        city: "Oia",
        image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e",
        description: "Experience magical sunsets and beautiful white-washed buildings in this romantic island getaway.",
        tags: ["romantic", "sunset", "island", "architecture"],
        category: "luxury",
        budget: "luxury",
        season: "summer",
        duration: "1-week",
        climate: "mediterranean",
        activities: ["sightseeing", "photography", "dining", "sailing"],
        rating: 4.9,
        reviews: 1250,
        isTrending: true,
        isFeatured: true,
        bestFor: "honeymoon",
        accommodationNearby: ["hotels", "luxury"],
        activityType: ["relaxation", "sightseeing"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Machu Picchu Trek",
        country: "Peru",
        city: "Cusco",
        image: "https://images.unsplash.com/photo-1526392060635-9d6019884377",
        description: "Hike the historic Inca Trail to discover the ancient ruins of Machu Picchu nestled in the Andes.",
        tags: ["hiking", "history", "ruins", "mountains"],
        category: "adventure",
        budget: "moderate",
        season: "all-season",
        duration: "1-week",
        climate: "temperate",
        activities: ["hiking", "exploring", "photography"],
        rating: 4.8,
        reviews: 890,
        isTrending: false,
        isFeatured: true,
        bestFor: "friends",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Kyoto Temples & Gardens",
        country: "Japan",
        city: "Kyoto",
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
        description: "Immerse yourself in traditional Japanese culture, stunning temples, and peaceful bamboo forests.",
        tags: ["culture", "temples", "food", "nature"],
        category: "cultural",
        budget: "moderate",
        season: "spring",
        duration: "2-weeks",
        climate: "temperate",
        activities: ["sightseeing", "dining", "cultural tours"],
        rating: 4.9,
        reviews: 2100,
        isTrending: true,
        isFeatured: true,
        bestFor: "couple",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["educational", "sightseeing", "photography"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["audio", "professional"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Serengeti Safari",
        country: "Tanzania",
        city: "Arusha",
        image: "https://images.unsplash.com/photo-1516426122078-c23e76319801",
        description: "Witness the great migration and spot the Big Five in their natural habitat.",
        tags: ["safari", "wildlife", "nature", "photography"],
        category: "wildlife",
        budget: "luxury",
        season: "all-season",
        duration: "1-week",
        climate: "tropical",
        activities: ["safari", "photography", "camping"],
        rating: 5,
        reviews: 650,
        isTrending: false,
        isFeatured: true,
        bestFor: "family",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography", "educational"],
        bestSeason: ["oct_dec", "jan_mar"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Maldives Overwater Bungalow",
        country: "Maldives",
        city: "Male",
        image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8",
        description: "Ultimate relaxation in crystal clear waters with direct lagoon access from your villa.",
        tags: ["beach", "relaxation", "snorkeling", "resort"],
        category: "luxury",
        budget: "luxury",
        season: "all-season",
        duration: "1-week",
        climate: "tropical",
        activities: ["snorkeling", "swimming", "spa", "dining"],
        rating: 4.9,
        reviews: 1400,
        isTrending: true,
        isFeatured: true,
        bestFor: "honeymoon",
        accommodationNearby: ["luxury"],
        activityType: ["relaxation", "adventure", "photography"],
        bestSeason: ["oct_dec", "jan_mar"],
        bestTime: ["morning", "evening", "all_day"],
        facilities: ["restrooms", "food_court", "wifi"],
        foodOptions: ["restaurant"],
        guidedTours: ["professional", "group"],
        languages: ["english"],
        transportMode: ["flight"]
    },
    {
        name: "Banff National Park",
        country: "Canada",
        city: "Banff",
        image: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce",
        description: "Explore breathtaking turquoise lakes, majestic mountains, and abundant wildlife.",
        tags: ["mountains", "lakes", "hiking", "nature"],
        category: "mountain",
        budget: "moderate",
        season: "summer",
        duration: "1-week",
        climate: "cold",
        activities: ["hiking", "kayaking", "wildlife spotting"],
        rating: 4.8,
        reviews: 3200,
        isTrending: true,
        isFeatured: true,
        bestFor: "family",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography", "relaxation"],
        bestSeason: ["apr_jun"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Bora Bora Lagoon",
        country: "French Polynesia",
        city: "Vaitape",
        image: "https://images.unsplash.com/photo-1533050487297-09b450131914",
        description: "Dive into turquoise lagoons and enjoy world-class luxury resorts.",
        tags: ["island", "beach", "scuba", "luxury"],
        category: "beach",
        budget: "luxury",
        season: "all-season",
        duration: "2-weeks",
        climate: "tropical",
        activities: ["scuba diving", "snorkeling", "sailing"],
        rating: 4.9,
        reviews: 450,
        isTrending: false,
        isFeatured: false,
        bestFor: "couple",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["relaxation", "adventure", "photography"],
        bestSeason: ["oct_dec", "jan_mar"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Reykjavik Northern Lights",
        country: "Iceland",
        city: "Reykjavik",
        image: "https://images.unsplash.com/photo-1520769945061-0a448c463865",
        description: "Chase the Aurora Borealis and soak in geothermal hot springs.",
        tags: ["aurora", "winter", "nature", "geothermal"],
        category: "adventure",
        budget: "moderate",
        season: "winter",
        duration: "1-week",
        climate: "cold",
        activities: ["aurora hunting", "hot springs", "glacier hiking"],
        rating: 4.7,
        reviews: 1800,
        isTrending: true,
        isFeatured: false,
        bestFor: "friends",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Swiss Alps Skiing",
        country: "Switzerland",
        city: "Zermatt",
        image: "https://images.unsplash.com/photo-1533282960533-51328aa2660a",
        description: "World-class skiing beneath the shadow of the iconic Matterhorn.",
        tags: ["skiing", "snow", "mountains", "winter"],
        category: "mountain",
        budget: "luxury",
        season: "winter",
        duration: "1-week",
        climate: "cold",
        activities: ["skiing", "snowboarding", "apres-ski"],
        rating: 4.9,
        reviews: 1100,
        isTrending: false,
        isFeatured: false,
        bestFor: "family",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography", "relaxation"],
        bestSeason: ["apr_jun"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Rome Ancient History",
        country: "Italy",
        city: "Rome",
        image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
        description: "Walk in the footsteps of gladiators and emperors in the Eternal City.",
        tags: ["history", "food", "architecture", "city"],
        category: "cultural",
        budget: "moderate",
        season: "spring",
        duration: "weekend",
        climate: "mediterranean",
        activities: ["sightseeing", "museums", "dining"],
        rating: 4.8,
        reviews: 5000,
        isTrending: false,
        isFeatured: false,
        bestFor: "couple",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["educational", "sightseeing", "photography"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["audio", "professional"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Bali Surf & Yoga",
        country: "Indonesia",
        city: "Canggu",
        image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4",
        description: "Perfect waves, daily yoga, and healthy cafes in a tropical paradise.",
        tags: ["surf", "yoga", "wellness", "beach"],
        category: "adventure",
        budget: "budget",
        season: "all-season",
        duration: "month",
        climate: "tropical",
        activities: ["surfing", "yoga", "cafe hopping"],
        rating: 4.6,
        reviews: 2500,
        isTrending: true,
        isFeatured: false,
        bestFor: "solo",
        state: "Bali",
        accommodationNearby: ["hotels", "budget", "luxury"],
        activityType: ["relaxation", "spiritual", "photography", "adventure"],
        bestSeason: ["apr_jun", "jul_sep"],
        bestTime: ["morning", "evening"],
        facilities: ["restrooms", "food_court", "atm", "shopping"],
        foodOptions: ["restaurant", "street_food"],
        guidedTours: ["professional", "group"],
        languages: ["english"],
        transportMode: ["flight", "car"]
    },
    {
        name: "Sahara Desert Camp",
        country: "Morocco",
        city: "Merzouga",
        image: "https://images.unsplash.com/photo-1534008897995-27a23e859048",
        description: "Sleep under a blanket of stars in luxury bedouin tents.",
        tags: ["desert", "camping", "stars", "camels"],
        category: "adventure",
        budget: "moderate",
        season: "autumn",
        duration: "weekend",
        climate: "desert",
        activities: ["camel riding", "stargazing", "dune bashing"],
        rating: 4.8,
        reviews: 800,
        isTrending: false,
        isFeatured: false,
        bestFor: "friends",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "New York City Lights",
        country: "USA",
        city: "New York",
        image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9",
        description: "The city that never sleeps offers endless entertainment, food, and culture.",
        tags: ["city", "urban", "shopping", "nightlife"],
        category: "city",
        budget: "luxury",
        season: "all-season",
        duration: "weekend",
        climate: "temperate",
        activities: ["shopping", "shows", "dining", "museums"],
        rating: 4.7,
        reviews: 8500,
        isTrending: true,
        isFeatured: false,
        bestFor: "friends",
        state: "New York",
        accommodationNearby: ["hotels", "budget", "luxury"],
        activityType: ["sightseeing", "educational", "photography", "relaxation"],
        bestSeason: ["jan_mar", "apr_jun", "jul_sep", "oct_dec"],
        bestTime: ["all_day"],
        facilities: ["restrooms", "food_court", "wifi", "atm", "shopping"],
        foodOptions: ["restaurant", "street_food"],
        guidedTours: ["audio", "professional", "group"],
        languages: ["english"],
        transportMode: ["flight", "train"]
    },
    {
        name: "Galapagos Islands Nature",
        country: "Ecuador",
        city: "Puerto Ayora",
        image: "https://images.unsplash.com/photo-1549887552-cb1071d3e5ca",
        description: "Encounter unique and fearless wildlife found nowhere else on earth.",
        tags: ["wildlife", "nature", "unique", "islands"],
        category: "wildlife",
        budget: "luxury",
        season: "all-season",
        duration: "2-weeks",
        climate: "tropical",
        activities: ["wildlife spotting", "snorkeling", "photography"],
        rating: 5,
        reviews: 350,
        isTrending: false,
        isFeatured: false,
        bestFor: "solo",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography", "educational"],
        bestSeason: ["oct_dec", "jan_mar"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Amsterdam Canals",
        country: "Netherlands",
        city: "Amsterdam",
        image: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4",
        description: "Cycle along picturesque canals and visit world-renowned art museums.",
        tags: ["city", "biking", "canals", "art"],
        category: "city",
        budget: "moderate",
        season: "spring",
        duration: "weekend",
        climate: "temperate",
        activities: ["biking", "museums", "boat tours"],
        rating: 4.6,
        reviews: 4200,
        isTrending: false,
        isFeatured: false,
        bestFor: "couple",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["sightseeing", "educational", "relaxation"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Patagonia Wilderness",
        country: "Argentina",
        city: "El Calafate",
        image: "https://images.unsplash.com/photo-1542385151-efd9000785a0",
        description: "Trek among stunning glaciers and dramatic mountain peaks at the end of the world.",
        tags: ["trekking", "glaciers", "wild", "mountains"],
        category: "adventure",
        budget: "moderate",
        season: "summer",
        duration: "2-weeks",
        climate: "cold",
        activities: ["trekking", "glacier tours", "photography"],
        rating: 4.9,
        reviews: 920,
        isTrending: true,
        isFeatured: false,
        bestFor: "solo",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography"],
        bestSeason: ["oct_dec"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Paris Romance",
        country: "France",
        city: "Paris",
        image: "https://images.unsplash.com/photo-1502602898657-3e907611593c",
        description: "Experience the magic of the Eiffel Tower, fine dining, and rich art history.",
        tags: ["romance", "art", "food", "city"],
        category: "cultural",
        budget: "moderate",
        season: "spring",
        duration: "1-week",
        climate: "temperate",
        activities: ["sightseeing", "dining", "museums"],
        rating: 4.7,
        reviews: 7000,
        isTrending: false,
        isFeatured: false,
        bestFor: "honeymoon",
        state: "Île-de-France",
        accommodationNearby: ["hotels", "luxury", "budget"],
        activityType: ["sightseeing", "educational", "photography", "relaxation"],
        bestSeason: ["apr_jun", "jul_sep"],
        bestTime: ["morning", "evening"],
        facilities: ["restrooms", "food_court", "wifi", "atm", "shopping"],
        foodOptions: ["restaurant"],
        guidedTours: ["audio", "professional", "group"],
        languages: ["english"],
        transportMode: ["flight", "train"]
    },
    {
        name: "Dubai Luxury Escape",
        country: "UAE",
        city: "Dubai",
        image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c",
        description: "Modern architecture, high-end shopping, and luxurious beach clubs.",
        tags: ["luxury", "shopping", "modern", "desert"],
        category: "luxury",
        budget: "luxury",
        season: "winter",
        duration: "1-week",
        climate: "desert",
        activities: ["shopping", "fine dining", "beach clubs", "safari"],
        rating: 4.5,
        reviews: 3100,
        isTrending: true,
        isFeatured: false,
        bestFor: "couple",
        state: "Dubai",
        accommodationNearby: ["hotels", "luxury", "budget"],
        activityType: ["sightseeing", "relaxation", "photography", "adventure"],
        bestSeason: ["oct_dec", "jan_mar"],
        bestTime: ["morning", "evening", "night"],
        facilities: ["restrooms", "food_court", "wifi", "atm", "shopping", "first_aid"],
        foodOptions: ["restaurant"],
        guidedTours: ["audio", "professional", "group"],
        languages: ["hindi", "english"],
        transportMode: ["flight", "car"]
    },
    {
        name: "Costa Rica Rainforest",
        country: "Costa Rica",
        city: "La Fortuna",
        image: "https://images.unsplash.com/photo-1518182170546-076616fd4cb8",
        description: "Zip-line through lush canopies and relax in natural hot springs.",
        tags: ["jungle", "nature", "eco", "wildlife"],
        category: "wildlife",
        budget: "moderate",
        season: "summer",
        duration: "1-week",
        climate: "tropical",
        activities: ["zip-lining", "hot springs", "wildlife spotting"],
        rating: 4.8,
        reviews: 1600,
        isTrending: false,
        isFeatured: false,
        bestFor: "family",
        accommodationNearby: ["hotels", "budget"],
        activityType: ["adventure", "photography", "educational"],
        bestSeason: ["oct_dec", "jan_mar"],
        bestTime: ["morning", "all_day"],
        facilities: ["restrooms"],
        foodOptions: ["street_food"],
        guidedTours: ["self_guided"],
        languages: ["hindi", "english"],
        transportMode: ["car", "bus"]
    },
    {
        name: "Goa Golden Beaches",
        country: "India",
        city: "Goa",
        image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2",
        description: "Vibrant nightlife, historic churches, and expansive sandy beaches.",
        tags: ["beach", "party", "culture", "budget"],
        category: "beach",
        budget: "budget",
        season: "winter",
        duration: "1-week",
        climate: "tropical",
        activities: ["swimming", "parties", "sightseeing"],
        rating: 4.4,
        reviews: 4800,
        isTrending: false,
        isFeatured: false,
        bestFor: "friends",
        state: "Goa",
        accommodationNearby: ["hotels", "budget", "luxury"],
        activityType: ["relaxation", "adventure", "photography", "sightseeing"],
        bestSeason: ["oct_dec", "jan_mar"],
        bestTime: ["morning", "evening"],
        facilities: ["restrooms", "food_court", "wifi", "atm", "shopping"],
        foodOptions: ["restaurant", "street_food"],
        guidedTours: ["self_guided", "group"],
        languages: ["hindi", "english", "regional"],
        transportMode: ["car", "train", "flight", "bus"]
    },
    {
        name: "surat",
        country: "India",
        state: "gujrat",
        city: "surat",
        image: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?q=80&w=2070&auto=format&fit=crop",
        description: "Experience the beauty of surat, gujrat.",
        tags: [],
        category: "city",
        type: "city",
        budget: "moderate",
        budgetPerPerson: "mid_range",
        entryFee: "free",
        season: "all-season",
        duration: "weekend",
        climate: "tropical",
        bestFor: "family",
        familyFriendly: true,
        fitnessLevel: "easy",
        photographyScore: "good",
        source: "manual",
        addedByAdmin: true
    },
    {
        name: "n vkdsb",
        country: "India",
        state: "dvfewkj",
        city: "n vkdsb",
        image: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?q=80&w=2070&auto=format&fit=crop",
        description: "Experience the beauty of n vkdsb, dvfewkj.",
        tags: [],
        category: "city",
        type: "city",
        budget: "moderate",
        budgetPerPerson: "mid_range",
        entryFee: "free",
        season: "all-season",
        duration: "weekend",
        climate: "tropical",
        bestFor: "family",
        familyFriendly: true,
        fitnessLevel: "easy",
        photographyScore: "good",
        source: "manual",
        addedByAdmin: true
    }
];

const importData = async () => {
    try {
        await Place.deleteMany(); // Clear existing places
        await Place.insertMany(places);
        console.log('20 Places seeded successfully!');
        process.exit();
    } catch (error) {
        console.error('Error seeding data:', error);
        process.exit(1);
    }
};

const destroyData = async () => {
    try {
        await Place.deleteMany();
        console.log('Places data destroyed!');
        process.exit();
    } catch (error) {
        console.error('Error destroying data:', error);
        process.exit(1);
    }
};

if (process.argv[2] === '-d') {
    destroyData();
} else {
    importData();
}
